name: "gitlab"
services:
  # This is GITLAB Server instance
  gitlab:
    container_name: gitlab
    image: "gitlab/gitlab-ce:18.3.2-ce.0"
    restart: unless-stopped
    hostname: "gitlab.example.com"
    extra_hosts:
      - "gitlab.example.com:172.20.0.10"
      - "registry.example.com:172.20.0.10"
    networks:
      net:
        ipv4_address: 172.20.0.10
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      interval: 15m
      timeout: 100s
      retries: 3
      start_period: 15m
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - "config:/etc/gitlab"
      - "logs:/var/log/gitlab"
      - "data:/var/opt/gitlab"
    shm_size: "256m"

  # This is RUNNER 
  gitlab-runner:
    container_name: gitlab-runner
    image: "gitlab/gitlab-runner:v18.3.1"
    restart: unless-stopped
    extra_hosts:
      - "gitlab.example.com:172.20.0.10"
      - "registry.example.com:172.20.0.10"
    volumes:
      - "runner_conf:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      net:
        ipv4_address: 172.20.0.11

# ALL options(network + volume)
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
volumes:
  config:
  logs:
  data:
  runner_conf: